behaviors:
  Wolf:
    trainer_type: poca
    hyperparameters:
      batch_size: 64
      buffer_size: 6400
      learning_rate: 0.0003
      beta: 0.007
      epsilon: 0.23
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 10000